spring.application.name=recharge

server.port=18090

server.address=0.0.0.0

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##recharge
spring.datasource.password=recharge
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

mybatis.mapper-locations=classpath:mybatis/mappers/*.xml
mybatis.type-aliases-package=com.recharge.**.vo
mybatis.configuration.map-underscore-to-camel-case=true

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.com.recharge.mapper=DEBUG
logging.level.org.mybatis=DEBUG

logging.level.jdbc=DEBUG
logging.level.jdbc.sqltiming=DEBUG